server:
  port: 8170

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-3-222-74-92.compute-1.amazonaws.com/da4hu24su0r0rp
    username: pvelwvwayoxiia
    password: fc6ae55e5e8716013e96fb6fb4836a0b0c039429d2c682080de4b7edc0fd8210
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect